// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9w7Cok1XDcqGp5pCkD9serPRtR_B5Twg',
    appId: '1:966932503665:web:decc652c67ea79a3590fd0',
    messagingSenderId: '966932503665',
    projectId: 'inventarisfit-89915',
    authDomain: 'inventarisfit-89915.firebaseapp.com',
    storageBucket: 'inventarisfit-89915.appspot.com',
    measurementId: 'G-FEP8BH6M3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaw-VFqXzdAfC_-JavlTuaYwfrHV4ggnA',
    appId: '1:966932503665:android:a8012b07340599d5590fd0',
    messagingSenderId: '966932503665',
    projectId: 'inventarisfit-89915',
    storageBucket: 'inventarisfit-89915.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD659iF9dt-KgNIbjn5zap7A_Z4CN8oDwU',
    appId: '1:966932503665:ios:03b8c07ba7763336590fd0',
    messagingSenderId: '966932503665',
    projectId: 'inventarisfit-89915',
    storageBucket: 'inventarisfit-89915.appspot.com',
    iosBundleId: 'com.example.flutterUilogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD659iF9dt-KgNIbjn5zap7A_Z4CN8oDwU',
    appId: '1:966932503665:ios:aeb8598755f05537590fd0',
    messagingSenderId: '966932503665',
    projectId: 'inventarisfit-89915',
    storageBucket: 'inventarisfit-89915.appspot.com',
    iosBundleId: 'com.example.flutterUilogin.RunnerTests',
  );
}
